# Generated by Django 4.0.4 on 2022-05-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistmovieapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='UserWatchlist',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='note',
            field=models.CharField(default='', max_length=500),
        ),
    ]
