# Generated by Django 4.0.4 on 2022-05-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistmovieapp', '0003_credentialsessiontmdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialsessiontmdb',
            name='api_key',
            field=models.CharField(max_length=50),
        ),
    ]
