# Generated by Django 4.0.4 on 2022-05-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistmovieapp', '0006_watchlist_poster_alter_watchlist_titlefilm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='titleFilm',
        ),
    ]
