# Generated by Django 4.0.4 on 2022-05-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistmovieapp', '0007_remove_watchlist_popularity_remove_watchlist_poster_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='credentialSessionTMDB',
        ),
    ]
